### ISSUE TITLE
Xibo/Docker: Depriciate Docker Parameter/Flag "links:"

### ISSUE THREAD

**Issue by Struppi** [xibosignage/xibo#3331]
I had now used 3 days to find out why my local test suite works but online version not. 

The problem it's hard to reproduce, for me on some installation it works on others not. don't know why. The enviroment where it don't work is an docker 25.0.1. on debian bullseye.

the most relevant error is in the cms-web container logs:
`cms-web_1         | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)`

it's not possible anymore to connect the running mysql server in the "cms-web" container via the alias "mysql". If you call a bash insider the web container you can connect the ip and even the "cms-db" alias and work with mysql -h cms-db -u cms -p inside the database. 

I am not a docker specialist so I need a bit to find out where the problem could be. I found [this](https://docs.docker.com/network/links/) docker documentation that the "link" flag should not use anymore. 

My solution was to extend the docker-compose.yml configuration of the cms-db service with an network alias this solve the problem and now I can connect from the cms-web to my cms-db with the "mysql" alias:
```
    cms-db:
        image: mysql:5.7
        volumes:
            - "./shared/db:/var/lib/mysql:Z"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
        networks:
           default:
             aliases:
                - mysql
```

Since I found in the xibo help forum a question from [2021 with the same issue](https://community.xibo.org.uk/t/xibo-cms-unable-accessing-mysql-docker-instance/25027) it would may help someone else and maybe the flag should be used instead the "links:" parameter in the cms-web service.
