### ISSUE TITLE
Twitter module - marquee effects don't work

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#558]
Other effects work just fine, but when you set effect to marquee (doesn't matter which one) it does nothing - it's the same as if it would be set to 'none'. This occur on both preview and the players.
This is only regarding twitter module, marquee effect works fine on text module.

Topic on community site:
https://community.xibo.org.uk/t/twitter-module-effects-not-working-on-windows/3001

**Comment by PeterMis** [comment]
1.7.5 still marquee = none, output wise // not sure if we changed it in 1.7.5 at the moment
1.8 - nearly there, only tweet text seems to be fine, with profile image, all returned images are shown at the beginning not before each tweet

**Comment by dasgarner** [comment]
Fixed the marquee bit in 1.7 - so that it now has the same issue as 1.8 (profile images stacked up).

That is due to this:

```css
p.profileimage img {width: 150px;float: left;padding-right: 20px;}
```

Change the template to this:
```css
p.profileimage img {width: 150px;padding-right: 20px;}
```

And its fine. I've submitted a backlog issue to look at this: #608
